/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Oskar "K1TT3N" Adamczyk (https://sketchfab.com/K1TT3N)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pine-tree-game-ready-dc3fbd9205cf4027a4455d1f415e0478
title: Pine Tree [Game-ready]
*/

import React, { useRef, useMemo, useContext, createContext } from "react";
import { useGLTF, Merged } from "@react-three/drei";

const context = createContext();
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF("./models/pine_tree_game-ready-transformed.glb");
  const instances = useMemo(
    () => ({
      TrunkTrunk: nodes.Trunk_Trunk_0,
      BranchesMTreeAtlas: nodes.Branches_M_TreeAtlas_0,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Model(props) {
  const instances = useContext(context);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <instances.TrunkTrunk />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <instances.BranchesMTreeAtlas />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/pine_tree_game-ready-transformed.glb");
